### ISSUE TITLE
Not compatible with SublimeLinter package

### ISSUE THREAD

**Issue by pymaldebaran** [kodLite/Oasis-Theme#1]
I'm using your theme and the wonderful C++ Starter Kit with Sublime Text 3 and it's from far my favorite environnement for C++ dev. Recently I installed the [SublimeLinter package](https://github.com/SublimeLinter/SublimeLinter3) because it's a very efficient way to keep my coding style to a good level.

It seems to have an incompatibility between these the oasis theme and SublimeLinter : when starting my editor here is what is shown in my console :

```
... blah blah blah ...
theme loaded
Traceback (most recent call last):
  File "/home/pym/.config/sublime-text-3/Packages/SublimeLinter/lint/util.py", line 258, in generate_color_scheme_async
    plist = ElementTree.XML(scheme_text)
  File "./xml/etree/ElementTree.py", line 1356, in XML
xml.etree.ElementTree.ParseError: syntax error: line 2, column 48
... blah blah blah ...
```

Currently I have not seen any other effect... but once a package has had some error while starting it's not really possible to rely on it :( and it's quite difficult to test all the functionnality of a linter !

I did not investigate further than a google search and it seems to be happening with other theme [for exemple](https://github.com/raphamorim/lucario/issues/8). Do you think it would be possible to fix this ?

**Comment by uncreative** [comment]
I have the same problem, I'm using the latest version available in package control. 
I have c++ Starter Kit installed. 
When I switch themes, the error goes away. 
Any advice? 

Thanks!

**Comment by kodLite** [comment]
To be honest I don't know where this error is coming from...

For my modest C++ experiments everything seems to work correctly with the C++ Starting Kit, Oasis Theme and Sublime Linter - CppCheck.

For now I can only recommend you to check this section of the documentation if you haven't done it yet : http://cppstartingkitproject-guide.readthedocs.org/en/latest/C++_Starting_Kit_Plugin--Recommandation--Prerequisite--Install_Cppcheck--How.html

For information I use Sublime Text 3 build 3065, it may have an impact, not sure.

I planned to completely rewrite the Oasis Theme scheme but this is not for now because I don't really have the time for it.

I hope it helps.

**Comment by asevich** [comment]
I had the same problem. 
The fix is easy, but since I'm no expert in xml I don't know what are implications of this change. However, I got rid of the error and I'm ok with that.

In file Oasis.tmTheme. 
Change line 2 from:
<!DOCTYPE plist PUBLIC "something@somewhere.ops">
to
<!DOCTYPE plist PUBLIC "" "something@somewhere.ops">

After that SublimeLinter doesn't throw any parsing errors.

Cheers
